name = "dou-lapcord"
author = "Dou"
version = "2.1.0"
display-name = "Lapcord"
description = "Discord Rich Presence extension for Lapce Editor."
wasm = "bin/lapcord.wasm"
icon = "assets/logo.png"
repository = "https://github.com/doupkg/lapcord"

[activation]
language = []
workspace-contains = ["*"]

[config."serverPath"]
default = ""
description = "Path to server. When empty, will download automatically"

# Editing
[config."lapcord.editing.details"]
default = ""
description = ""

[config."lapcord.editing.largeImageText"]
default = ""
description = ""

[config."lapcord.editing.showTimestamp"]
default = true
description = ""

[config."lapcord.editing.smallImageText"]
default = ""
description = ""

[config."lapcord.editing.state"]
default = "Editing {filename}"
description = ""

# Idle
[config."lapcord.idle.details"]
default = ""
description = ""

[config."lapcord.idle.largeImageText"]
default = ""
description = ""

[config."lapcord.idle.showTimestamp"]
default = true
description = ""

[config."lapcord.idle.smallImageText"]
default = ""
description = ""

[config."lapcord.idle.state"]
default = "Idle"
description = ""

[config."lapcord.idle.timeout"]
default = 60
description = "In seconds. Min 15s"
