name = "dou.lapcord"
author = "Dou"
version = "0.0.4"
description = "Discord Rich Presence extension for Lapce Editor."
display-name = "Lapcord"
wasm = "bin/lapcord.wasm"
icon = "assets/logo.png"
repository = "https://github.com/dzlib/lapcord"

[activation]
language = []
workspace-contains = ["*"]

[config."lsp.serverPath"]
default = ""
description = "Path to custom LSP executable"

[config."lsp.serverArgs"]
default = []
description = ""